version: "3.7"
services:
  jk-di-es1:
    hostname: jk-di-es1
    image: harbor.jkservice.org/di/security-elasticsearch:7.14.2
    container_name: jk-di-es1
#    user: "0:0"
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      # 日志方式使用默认json-file
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - jk-di-es-data1:/usr/share/elasticsearch/data
    networks:
      - devops-compose
    environment:
      - cluster.initial_master_nodes=jk-di-es1,jk-di-es2,jk-di-es3
      - discovery.seed_hosts=jk-di-es1:9300,jk-di-es2:9300,jk-di-es3:9300
      - node.name=jk-di-es1
      - network.host=0.0.0.0
      - network.bind_host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Authorization,X-Requested-With,Content-Length,Content-Type
      - bootstrap.memory_lock=false
      # 开启认证和授权
      - xpack.security.enabled=true
      # 集群内部的通信
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      # 设置运行模式
      - RUN_MODE=cluster
      # 设置用户和密码
      - ES_USER=jkstack
      - ES_PASSWORD=123qweASD
      - search.max_buckets=500000
      - indices.fielddata.cache.size=30%
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
      - indices.breaker.total.limit=80%
      - indices.breaker.fielddata.limit=60%
      - indices.breaker.request.limit=60%
      - cluster.max_shards_per_node=10000
      # 设置节点对应的角色
      - node.master=true
      - node.ingest=true
      - node.data=true
      - node.ml=false
      - xpack.ml.enabled=false
  jk-di-es2:
    hostname: jk-di-es2
    image: harbor.jkservice.org/di/security-elasticsearch:7.14.2
    container_name: jk-di-es2
    #    user: "0:0"
   # ports:
   #   - "9200:9200"
   #   - "9300:9300"
    logging:
      # 日志方式使用默认json-file
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - jk-di-es-data2:/usr/share/elasticsearch/data
    networks:
      - devops-compose
    environment:
      - cluster.initial_master_nodes=jk-di-es1,jk-di-es2,jk-di-es3
      - discovery.seed_hosts=jk-di-es1:9300,jk-di-es2:9300,jk-di-es3:9300
      - node.name=jk-di-es2
      - network.host=0.0.0.0
      - network.bind_host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Authorization,X-Requested-With,Content-Length,Content-Type
      - bootstrap.memory_lock=false
      # 用户认证授权
      - xpack.security.enabled=true
      # 集群内部的通信
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      # 运行模式
      - RUN_MODE=cluster
      # 设置用户和密码
      - ES_USER=jkstack
      - ES_PASSWORD=123qweASD
      - search.max_buckets=500000
      - indices.fielddata.cache.size=30%
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
      - indices.breaker.total.limit=80%
      - indices.breaker.fielddata.limit=60%
      - indices.breaker.request.limit=60%
      - cluster.max_shards_per_node=10000
      # 设置节点对应的角色
      - node.master=true
      - node.ingest=true
      - node.data=true
      - node.ml=false
      - xpack.ml.enabled=false
  jk-di-es3:
    hostname: jk-di-es3
    image: jharbor.jkservice.org/di/security-elasticsearch:7.14.2
    container_name: jk-di-es3
    #    user: "0:0"
   # ports:
   #   - "9200:9200"
   #  - "9300:9300"
    logging:
      # 日志方式使用默认json-file
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - jk-di-es-data3:/usr/share/elasticsearch/data
    networks:
      - devops-compose
    environment:
      - cluster.initial_master_nodes=jk-di-es1,jk-di-es2,jk-di-es3
      - discovery.seed_hosts=jk-di-es1:9300,jk-di-es2:9300,jk-di-es3:9300
      - node.name=jk-di-es3
      - network.host=0.0.0.0
      - network.bind_host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Authorization,X-Requested-With,Content-Length,Content-Type
      - bootstrap.memory_lock=false
      # 用户认证授权
      - xpack.security.enabled=true
      # 集群内部的通信
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      # 运行模式
      - RUN_MODE=cluster
      # 设置用户和密码
      - ES_USER=jkstack
      - ES_PASSWORD=123qweASD
      - search.max_buckets=500000
      - indices.fielddata.cache.size=30%
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
      - indices.breaker.total.limit=80%
      - indices.breaker.fielddata.limit=60%
      - indices.breaker.request.limit=60%
      - cluster.max_shards_per_node=10000
      # 设置节点对应的角色
      - node.master=false
      - node.ingest=true
      - node.data=true
      - node.ml=false
      - xpack.ml.enabled=false


networks:
  devops-compose:
    external: true


volumes:
  jk-di-es-data1:
  jk-di-es-data2:
  jk-di-es-data3:
