version: "3.7"
services:
   jenkins2.60.3:
     #image: jenkins/jenkins:2.263.1-lts-centos7
     image: jkstack-jenkins:1.0.0
     restart: always
     container_name: jenkins2.60.3
     ports:
       - 9999:8080
     volumes:
       - ./data:/var/jenkins_home
     #environment:
      # - TZ='Asia/Shanghai'
     networks:
       - devops

networks:
  devops:
    external: true