version: '3.7'
services:
  di-nacos:
    hostname: di-nacos
    image: harbor.jkservice.org/di/nacos:1.3.2
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      # 日志方式使用默认json-filefile
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "2"
    ports:
      - 8848:8848
    environment:
      - JVM_XMX=1g
      - JVM_XMS=1g
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      # mysql数据库配置
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_HOST=di-mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123qweASD
      # nacos开启权限操作
      #- NACOS_AUTH_ENABLE=true
    volumes:
      - $PWD/nacos-logs:/app/data/nacos/logs
    networks:
      - devops


networks:
  devops:
    external: true